# Generated by Django 4.2.6 on 2023-11-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_alter_candidate_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='que_id',
            new_name='qid',
        ),
    ]
